pipeline {
    agent any

     tools {
            maven 'maven 3'
     }
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'
                sh 'make'
            }
        }
        stage('maven clean build') {
            steps {
               sh 'mvn clean package'
            }
        }
    }
    post {
        always {
            echo 'I will always say Hello again! in master branch in first module'
        }
    }
}